### ISSUE TITLE
Bare minimal Installation

### ISSUE THREAD

**Issue by dipterix** [BBillot/SynthSR#10]
Is there any way that I can do just install for applying pre-trained models to predict? FreeSurfer build for SynthSR does not work on Windows nor ARM based CPU (basically all new OSX).

**Comment by BBillot** [comment]
Yes sure, you can install the code distributed here as well as the required libraries listed in requirements.txt and the trained models. Everything is explained in the README.

If you need additional guidelines for the installation, you can follow steps 1,2 and 4 of the installation section for SynthSeg ([https://github.com/BBillot/SynthSeg](https://github.com/BBillot/SynthSeg)), which has the same requirements.
