### ISSUE TITLE
Installation of the correct requirements

### ISSUE THREAD

**Issue by carlouic** [BBillot/SynthSR#11]
Hi all, 
Thanks for this incredible project. 
I am able to make the model run using the FSL command line, and now I wanted to try to make also the github source code work on my laptop. I am facing issues in the moment when I try to pip install the requirements, and I get this huge error : 

ERROR: Command errored out with exit status 1:
     command: /home/carlo/miniconda3/bin/python /home/carlo/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp5hj9q35a
         cwd: /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f
    Complete output (61 lines):
    Running from numpy source directory.
    <string>:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
    /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py:75: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      required_version = LooseVersion('0.29.14')
    /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py:77: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      if LooseVersion(cython_version) < required_version:
    warning: /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
    warning: /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
    warning: /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
    warning: /tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/numpy/__init__.pxd:17:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
    
    Error compiling Cython file:
    ------------------------------------------------------------
    ...
            for i in range(1, RK_STATE_LEN):
                self.rng_state.key[i] = val[i]
            self.rng_state.pos = i
    
            self._bitgen.state = &self.rng_state
            self._bitgen.next_uint64 = &mt19937_uint64
                                       ^
    ------------------------------------------------------------
    
    _mt19937.pyx:138:35: Cannot assign type 'uint64_t (*)(void *) except? -1 nogil' to 'uint64_t (*)(void *) noexcept nogil'
    Processing numpy/random/_bounded_integers.pxd.in
    Processing numpy/random/mtrand.pyx
    Processing numpy/random/_common.pyx
    Processing numpy/random/_bit_generator.pyx
    Processing numpy/random/_mt19937.pyx
    Traceback (most recent call last):
      File "/tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py", line 238, in <module>
        main()
      File "/tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "/tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "/tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "/tmp/pip-install-kg4x1st3/numpy_56d0f5d74adf427d9bacc56e1a100c9f/tools/cythonize.py", line 80, in process_pyx
        subprocess.check_call(
      File "/home/carlo/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/home/carlo/miniconda3/bin/python', '-m', 'cython', '-3', '--fast-fail', '-o', '_mt19937.c', '_mt19937.pyx']' returned non-zero exit status 1.
    Cythonizing sources
    Traceback (most recent call last):
      File "/home/carlo/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/home/carlo/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/carlo/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 151, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-h0s7068_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-h0s7068_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 487, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-h0s7068_/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
        exec(code, locals())
      File "<string>", line 488, in <module>
      File "<string>", line 469, in setup_package
      File "<string>", line 275, in generate_cython
    RuntimeError: Running cythonize failed!
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/84/1e/ff467ac56bfeaea51d4a2e72d315c1fe440b20192fea7e460f0f248acac8/numpy-1.18.2.zip#sha256=e7894793e6e8540dbeac77c87b489e331947813511108ae097f1715c018b8f3d (from https://pypi.org/simple/numpy/) (requires-python:>=3.5). Command errored out with exit status 1: /home/carlo/miniconda3/bin/python /home/carlo/miniconda3/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp5hj9q35a Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement numpy==1.18.2 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0, 1.13.1, 1.13.3, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5, 1.20.0, 1.20.1, 1.20.2, 1.20.3, 1.21.0, 1.21.1, 1.21.2, 1.21.3, 1.21.4, 1.21.5, 1.21.6, 1.22.0, 1.22.1, 1.22.2, 1.22.3, 1.22.4, 1.23.0rc1, 1.23.0rc2, 1.23.0rc3, 1.23.0, 1.23.1, 1.23.2, 1.23.3, 1.23.4, 1.23.5, 1.24.0rc1, 1.24.0rc2, 1.24.0, 1.24.1, 1.24.2, 1.24.3, 1.24.4, 1.25.0rc1, 1.25.0, 1.25.1)
ERROR: No matching distribution found for numpy==1.18.2

I remember I faced something like this when trying to install synthseg as well, however the command line you provided over there has been very useful to proceed:

conda create -n synthseg_38 python=3.8 tensorflow-gpu=2.2.0 keras=2.3.1 nibabel matplotlib -c anaconda -c conda-forge

could you provide something like that for synthsr as well? thatd be very useful. thanks!

**Comment by BBillot** [comment]
Hi,
by FSL you mean FreeSurfer right ? ;)
Here it doesn't work because you have python 3.9 and the requirements listed here are for python 3.6. But you can actually use the same virtual environment as for SynthSeg, because both tools use the same libraries/requirements.
Hope this helps
Benjamin
