### ISSUE TITLE
Training model for SR

### ISSUE THREAD

**Issue by wendy-xiaozong** [BBillot/SynthSR#12]
Hi Benjamin,

Thanks for this wonderful work! I am also developing a method for MR SR problem and using your method as a compared method.

I am training SynthSR on another dataset using [tutorials/7-training.py](https://github.com/BBillot/SynthSR/blob/main/scripts/tutorials/7-training.py) and using the .h5 saved by this training file on the [scripts/predict_command_line.py](https://github.com/BBillot/SynthSR/blob/main/scripts/predict_command_line.py) file to super-resolution on low-resolution MRI. However, I run into this error:
```
ValueError: axes don't match array
```

I guess this is because the model weights are saved by the `training.py` file didn't exactly match the model in the `predict_command_line.py`. Could you point me out how to convert the saved model into the right version for the `predict_command_line.py` file?

Thanks! I have been sucked into this issue for a few days.

Jueqi

**Comment by BBillot** [comment]
Okay I can see some errors by SynthSR, but it would have been interesting to add the input image, just to see where you started from.

SynthSR was trained to output 1mm MPRAGE that are intensity-normalised just like in FreeSurfer. So I don't know the sequence of the 1mm T1s used in IXI, but maybe for fair comparison, you should compare the output of SynthSR against the output of the 1mm images processed by FreeSurfer ?
But yeah, an alternative solution is to retrain SynthSR on IXI. Note that if you want to retrain on IXI, you will need corresponding label maps with labels for cerebral and extra-cerebral regions.

**Comment by wendy-xiaozong** [comment]
The prediction error does exist, but I think the lower result (SSIM and PSNR) is mainly from the intensity shift. For now, I compare the output of SynthSR with the image preprocess from [UniRes](https://github.com/brudfors/UniRes). I do that just to get the input to match my own method.

So this is the input image; I process it with the nearest algorithm. (I modify the cropped area to make two images aligned).
![IXI_synthsr_example](https://github.com/BBillot/SynthSR/assets/32104051/27e7ff65-8dab-41d3-876b-a54b79629827)

Can I ask which command you use from FreeSurfer to process those 1mm MPRAGE?

Thanks!

**Comment by BBillot** [comment]
We used the recon-all command:
https://surfer.nmr.mgh.harvard.edu/fswiki/recon-all
