### ISSUE TITLE
No module named 'keras.legacy'

### ISSUE THREAD

**Issue by sw3866** [BBillot/SynthSR#16]
Hello Benjamin,

Good afternoon. I'm experiencing **ModuleNotFoundError: no module named "keras.legacy" when running a single line command for prediction**. Which version of Keras should I use to solve this problem? The latest version of Keras doesn't seem to have keras.legacy anymore.

Best,
Siyan

**Comment by BBillot** [comment]
Hi!
please use the same libraries (keras, etc.) as for SynthSeg [https://github.com/BBillot/SynthSeg](url). This should solve your problem :)

**Comment by sw3866** [comment]
I used the SythSeg requirement_python3.8.txt on a linux system, but there is still an issue during the installation process:
 

ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

Could you help with this? :)
Thanks,

**Comment by BBillot** [comment]
Hey I've updated the installation instructions. Can you please let me know if it works for you for a fresh installation ? Thanks!
