### ISSUE TITLE
Hyperostosis affecting older adult scans

### ISSUE THREAD

**Issue by johnaeanderson** [BBillot/SynthSR#2]
Hi, thanks for creating such an amazing tool! 

I've used the FreeSurfer implementation & am running into issues when attempting to use the HyperFine algorithm with older adult MRIs. In many older adults, the inner table of the skull starts to grow & this affects the intensity of the image. In many cases, the algorithm grabs extra "brain" from these (largely frontal) regions thinking that this high-intensity region must be white matter since there is another skull layer beyond this.  

Using the T1-only algorithm doesn't produce this error (though detail is lost in the rest of the brain - see attached). 

In the past, I've had difficulty skull stripping older adult brains because of this, but I've found that HD-BET https://github.com/MIC-DKFZ/HD-BET seems to handle this well - so if there's an issue of deciding what is/isn't brain, this might be a workaround.

In the meantime, I'll use base SynthSR since that still produces better results than anything I've seen, but at some stage, if there is an update that allows HyperFine to run with older adults I'd be over the moon (I realize this is an edge case & might not be a priority). 

All of which is to say, cheers & thanks!

John
![Hyperfine 001](https://user-images.githubusercontent.com/3432462/130811695-cc09d936-9344-4dcd-a69a-5d220eea2461.jpeg)

**Comment by BBillot** [comment]
sorry for the late answer, I don't look at GitHub comments very often...
Thanks a lot for the kind words.
As you said, I'm not sure this is high priority right now, but I will keep this in my mind and add it to the long todo list for SynthSR/SynthSeg !
Thanks again,
Benjamin
