### ISSUE TITLE
processing Hyperfine scans

### ISSUE THREAD

**Issue by julien-dubois-k** [BBillot/SynthSR#3]
I have some images from Hyperfine, which I'd like to process to get "super resolution" scans. I actually have 3 T1-weighted and 3 T2-weighted scans, i.e. I do have high-resolution (well, 1.5mm) in each plane.

I tried your pretrained model on each pair of scans (it doesn't seem that you support using multiple images of a single modality). 
- T1 ax and T2 ax
- T1 cor and T2 cor
- T1 sag and T2 sag

The output is quite different for each pair of scans (and none of the outputs really matches the reference HR T1-MPRAGE that I have). So I'm coming to you for advice to move forward.

I know that your model requires the FSE sequence for T1 and T2. Here is what I have:
- for T1, `T1_Gray_White_Contrast_(DL)`
- for T2, `T2-Weighted_FSE_(DL)`
So, perhaps I have the wrong sequence for the T1 scan. 
Could I retrain the model? I looked at the tutorials (5 and 6) but couldn't quite see what knobs to turn.

Are your models brain-specific? From the training images in the data folder I would assume so. I am interested in getting super resolution for the whole head, i.e. also scalp, skull and CSF. Would I need to retrain the models with my own whole head images? 

Finally -- is there an easy way to combine several scans of the same modality?

**Comment by BBillot** [comment]
Hello,

the plain SynthSR doesn't handle multi-modality cases. For this reason, we trained another model only dedicated to Hyperfine scans, with stricter requirements:
- it is for the "standard" Hyperfine T1 and T2 acquisitions (FSE sequence) at 1.5x1.5x5mm axial resolution (so don't use it with coronal or sagittal scans).
- If there is motion between the T1 and T2 scans, the T2 needs to be pre-registered to the space of the T1 (see README file for more explanations).

This model is supposed to handle whole brain scans, so it should work in your case. And I don't understand what you mean by "is there an easy way to combine several scans of the same modality?". You can super-resolve several scans at the same time by putting them in the same folder and calling synthsr on this folder.

Hope this helps,
Benjamin

**Comment by julien-dubois-k** [comment]
Hi Benjamin, 

> it is for the "standard" Hyperfine T1 and T2 acquisitions (FSE sequence) at 1.5x1.5x5mm axial resolution (so don't use it with coronal or sagittal scans).

thank you, I missed the axial constraint.

> And I don't understand what you mean by "is there an easy way to combine several scans of the same modality?" You can super-resolve several scans at the same time by putting them in the same folder and calling synthsr on this folder.

What I saw is that if there are multiple images in a folder, they are resolved one by one (and in the case of two folders with T1 and T2, they are resolved pair by pair, in order). So say I had two axial T1s from Hyperfine, I'd need to average them myself first before running these models. 

If I wanted to retrain the model on e.g. the coronal or sagittal scans, could I do that? Thank you!

**Comment by BBillot** [comment]
sorry for the (very) late answer.

> So say I had two axial T1s from Hyperfine, I'd need to average them myself first before running these models.
Correct.

> If I wanted to retrain the model on e.g. the coronal or sagittal scans, could I do that?
Yes, sure. You'll need a bunch of training segmentation maps (with labels for cerebral and extra-cerebral structures), and probably a segmentation network.
