### ISSUE TITLE
Dataset Usage

### ISSUE THREAD

**Issue by BSYMAHESH** [BBillot/SynthSR#5]
Hi, Thanks for sharing your work here. 

You mentioned that the images present in this repo are pre-processed publicly available data and labels are generated using free surfer software. As you kept Apache 2.0 license to this repo, can I use this derived dataset present in this repository or Is there any restrictions on original publicly available dataset ??

**Comment by BBillot** [comment]
You can use the data, but please cite this paper:

[2] [A novel in vivo atlas of human hippocampal subfields usinghigh-resolution 3 T magnetic resonance imaging](https://www.sciencedirect.com/science/article/abs/pii/S1053811913001237)
J. Winterburn, J. Pruessner, S. Chavez, M. Schira, N. Lobaugh, A. Voineskos, M. Chakravarty
NeuroImage (2013)
