### ISSUE TITLE
Error: Illegal instruction: 4

### ISSUE THREAD

**Issue by leiliew** [BBillot/SynthSR#6]
Hi,
I just tried using SynthSR installed in the FreeSurfer dev version. Freeview works fine. When I try the base command, I get the following error:
```
mri_synthsr --i input.nii.gz --o output.nii.gz
zsh: illegal hardware instruction  mri_synthsr --i input.nii.gz --o
```

If I just try to call mri_synthsr, I also get the error:
```
sh-3.2$ mri_synthsr
Illegal instruction: 4
```

I'm using Mac 12.5.1 (Monterey). Any help is appreciated - thanks!

**Comment by BBillot** [comment]
Hi,

that looks to me like a FreeSurfer installation/incompatibility problem.

I think you should directly email the FreeSurfer development team, they will be able to help you with this. Also they usually respond pretty fast.
https://surfer.nmr.mgh.harvard.edu/fswiki/FreeSurferSupport
