### ISSUE TITLE
donwsampled spacing in SybthSR

### ISSUE THREAD

**Issue by 11710615** [BBillot/SynthSR#8]
Hello, thanks for your fantastic work.
I have a question about the downsampled spacing setting in training. Whether you train one model for different spacing randomly selected from [3, 5, 7] (different minibatch with changeable spacing) or train three models for each spacing?

**Comment by BBillot** [comment]
Hi and thanks for the interest !
So it's actually neither of these things.
We only train one model, and during training, the simulated resolution is randomly selected between 1 and 7 at each mini-batch. The trained model is then evaluated at test time with scans at different resolutions (3, 5, 7).
Hope this helps
Benjamin
