### ISSUE TITLE
Cerebellum

### ISSUE THREAD

**Issue by rnorlund** [BBillot/SynthSR#9]
Would it be kosher to use the synthSR generated images for cerebellar GMV evaluations or is this meant strictly for cortical areas of interest?
Your thoughts/opinion would be appreciated!

**Comment by BBillot** [comment]
Hi,
yes you can absolutely use this tool for cerebellar applications, since it has been trained the same way for cerebral and cerebellar regions.

**Comment by rnorlund** [comment]
Thank you!
